LOCAL_PATH := $(call my-dir)
LOCAL_INCLUDE_PATH := $(LOCAL_PATH)/include

include $(CLEAR_VARS)

LOCAL_MODULE    := avcodec
LOCAL_SRC_FILES := $(LOCAL_PATH)/lib/libavcodec.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_INCLUDE_PATH)
LOCAL_C_INCLUDES += $(LOCAL_INCLUDE_PATH)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE    := avformat
LOCAL_SRC_FILES := $(LOCAL_PATH)/lib/libavformat.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_INCLUDE_PATH)
LOCAL_C_INCLUDES += $(LOCAL_INCLUDE_PATH)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE    := swscale
LOCAL_SRC_FILES := $(LOCAL_PATH)/lib/libswscale.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_INCLUDE_PATH)
LOCAL_C_INCLUDES += $(LOCAL_INCLUDE_PATH)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE    := avutil
LOCAL_SRC_FILES := $(LOCAL_PATH)/lib/libavutil.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_INCLUDE_PATH)
LOCAL_C_INCLUDES += $(LOCAL_INCLUDE_PATH)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE    := avfilter
LOCAL_SRC_FILES := $(LOCAL_PATH)/lib/libavfilter.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_INCLUDE_PATH)
LOCAL_C_INCLUDES += $(LOCAL_INCLUDE_PATH)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE    := swresample
LOCAL_SRC_FILES := $(LOCAL_PATH)/lib/libswresample.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_INCLUDE_PATH)
LOCAL_C_INCLUDES += $(LOCAL_INCLUDE_PATH)
include $(PREBUILT_STATIC_LIBRARY)